# AdvancedWeapons Config
# Messages
reset-msg: "&6[AdvancedWeapons] &aConfig reset."
reload-msg: "&6[AdvancedWeapons] &aConfig reloaded."
update-msg: "&6[AdvancedWeapons] &aConfig updated."
no-permission-msg: "&cYou do not have permission to use &4/{cmd}&c."
insufficient-dust-msg: "&cYou do not have enough Dust."
insufficient-space-msg: "&cDropped items that do not fit in your inventory."
# Features
update-check: true
durability: false
cake: true
discord-message: true
# Dust
enable-dust-xp: true
dust-xp: 85
enable-dust-money: true
dust-money: 100
enable-dust-material: true
dust-material: GOLD_INGOT
dust-trade: 1
dust-item:
  - "&7This Dust has magical properties"
  - "&7which make it a valuable currency."
dust-obtainable:
  - ANCIENT_DEBRIS:50
  - DIAMOND_ORE:40
  - EMERALD_ORE:35
  - LAPIS_ORE:25
  - REDSTONE_ORE:20
  - NETHER_GOLD_ORE:15
  - GOLD_ORE:15
  - IRON_ORE:10
  - NETHER_QUARTZ_ORE:5
  - COAL_ORE:5
# Weapons
weapon:
  the-destroyer:
    cost: 20
  the-slayer:
    msg: true
    cost: 20
  the-dropper:
    msg: true
    cost: 12
  fireball-launcher:
    msg: true
    cost: 10
  the-skeletal-sword:
    msg: true
    cost: 14
  ice-chunk:
    msg: true
    cost: 12
  spirit-leash:
    msg: true
    cost: 14
# Machines
machine:
  port-a-wall:
    cost: 20
  autominer:
    cost: 160
# Custom Enchantments
enchant:
  rush-i:
    name: "&eRush I"
    lore:
      - "&7Gives you a quick rush of speed."
      - "&7Speed I - 4s"
    chance: 10
    cost: 8
    type: weapon
    events:
      - interact
    function: potion
    effects:
      - SPEED
    duration: 4
    amplifier: 0
  rush-ii:
    name: "&eRush II"
    lore:
      - "&7Gives you a quick rush of speed."
      - "&7Speed I - 6s"
    chance: 10
    cost: 16
    type: weapon
    events:
      - interact
    function: potion
    effects:
      - SPEED
    duration: 6
    amplifier: 0
  rush-iii:
    name: "&eRush III"
    lore:
      - "&7Gives you a quick rush of speed."
      - "&7Speed I - 8s"
    chance: 10
    cost: 32
    type: weapon
    events:
      - interact
    function: potion
    effects:
      - SPEED
    duration: 8
    amplifier: 0
  bounce-i:
    name: "&eBounce I"
    lore:
      - "&7Lets you jump to new heights."
      - "&7Bounce I - 4s"
    chance: 1
    cost: 8
    type: weapon
    events:
      - interact
    function: potion
    effects:
      - JUMP
    duration: 4
    amplifier: 0
  bounce-ii:
    name: "&eBounce II"
    lore:
      - "&7Lets you jump to new heights."
      - "&7Bounce I - 6s"
    chance: 10
    cost: 16
    type: weapon
    events:
      - interact
    function: potion
    effects:
      - JUMP
    duration: 6
    amplifier: 0
  bounce-iii:
    name: "&eBounce III"
    lore:
      - "&7Lets you jump to new heights."
      - "&7Bounce I - 8s"
    chance: 10
    cost: 32
    type: weapon
    events:
      - interact
    function: potion
    effects:
      - JUMP
    duration: 8
    amplifier: 0
  hyper-i:
    name: "&eHyper I"
    lore:
      - "&7Hit faster when hyper."
      - "&7Haste I - 4s"
    chance: 10
    cost: 8
    type: weapon
    events:
      - interact
    function: potion
    effects:
      - FAST_DIGGING
    duration: 4
    amplifier: 0
  hyper-ii:
    name: "&eHyper II"
    lore:
      - "&7Hit faster when hyper."
      - "&7Haste I - 6s"
    chance: 1
    cost: 16
    type: weapon
    events:
      - interact
    function: potion
    effects:
      - FAST_DIGGING
    duration: 6
    amplifier: 0
  hyper-iii:
    name: "&eHyper III"
    lore:
      - "&7Hit faster when hyper."
      - "&7Haste I - 8s"
    chance: 10
    cost: 32
    type: weapon
    events:
      - interact
    function: potion
    effects:
      - FAST_DIGGING
    duration: 8
    amplifier: 0
  plague-i:
    name: "&ePlague I"
    lore:
      - "&7Inflicts poison on your enemies."
      - "&7Poison I - 4s"
    chance: 10
    cost: 8
    type: weapon
    events:
      - attackother
    function: potion
    effects:
      - POISON
    duration: 4
    amplifier: 0
    immune:
      - poison
  plague-ii:
    name: "&ePlague II"
    lore:
      - "&7Inflicts poison on your enemies."
      - "&7Poison I - 8s"
    chance: 10
    cost: 16
    type: weapon
    events:
      - attackother
    function: potion
    effects:
      - POISON
    duration: 6
    amplifier: 0
    immune:
      - poison
  plague-iii:
    name: "&ePlague III"
    lore:
      - "&7Inflicts poison on your enemies."
      - "&7Poison I - 8s"
    chance: 10
    cost: 32
    type: weapon
    events:
      - attackother
    function: potion
    effects:
      - POISON
    duration: 8
    amplifier: 0
    immune:
      - poison
  end-ender-i:
    name: "&eEnd Ender I"
    lore:
      - "&7Deals more damage to endermen"
      - "&7and endermites"
      - "&7+1 damage"
    chance: 100
    cost: 8
    type: weapon
    events:
      - attackother
    function: damage
    effects:
      - 1
    affected:
      - ENDERMAN
      - ENDERMITE
  end-ender-ii:
    name: "&eEnd Ender II"
    lore:
      - "&7Deals more damage to endermen"
      - "&7and endermites"
      - "&7+1.5 damage"
    chance: 100
    cost: 16
    type: weapon
    events:
      - attackother
    function: damage
    effects:
      - 1.5
    affected:
      - ENDERMAN
      - ENDERMITE
  end-ender-iii:
    name: "&eEnd Ender III"
    lore:
      - "&7Deals more damage to endermen"
      - "&7and endermites"
      - "&7+2 damage"
    chance: 100
    cost: 32
    type: weapon
    events:
      - attackother
    function: damage
    effects:
      - 2
    affected:
      - ENDERMAN
      - ENDERMITE
  butcher-i:
    name: "&eButcher I"
    lore:
      - "&7Deals more damage"
      - "&7to farm animals."
      - "&7+0.5 damage"
    chance: 100
    cost: 8
    type: weapon
    events:
      - attackother
    function: damage
    effects:
      - 0.5
    affected:
      - COW
      - PIG
      - SHEEP
      - CHICKEN
      - HORSE
      - DONKEY
      - MULE
  butcher-ii:
    name: "&eButcher II"
    lore:
      - "&7Deals more damage"
      - "&7to farm animals."
      - "&7+1 damage"
    chance: 100
    cost: 16
    type: weapon
    events:
      - attackother
    function: damage
    effects:
      - 1
    affected:
      - COW
      - PIG
      - SHEEP
      - CHICKEN
      - HORSE
      - DONKEY
      - MULE
  butcher-iii:
    name: "&eButcher III"
    lore:
      - "&7Deals more damage"
      - "&7to farm animals."
      - "&7+1.5 damage"
    chance: 100
    cost: 32
    type: weapon
    events:
      - attackother
    function: damage
    effects:
      - 1.5
    affected:
      - COW
      - PIG
      - SHEEP
      - CHICKEN
      - HORSE
      - DONKEY
      - MULE
  tolerance-i:
    name: "&eTolerance I"
    lore:
      - "&7Gives resistance after taking more"
      - "&7than a certain amount of damage."
      - "&7Resistance I at 40% health - 4s"
    chance: 25
    cost: 8
    type: armor
    events:
      - armorself
    function: potion
    effects:
      - DAMAGE_RESISTANCE
    duration: 4
    amplifier: 0
    thresholdself: 40
  tolerance-ii:
    name: "&eTolerance II"
    lore:
      - "&7Gives resistance after taking more"
      - "&7than a certain amount of damage."
      - "&7Resistance I at 40% health - 6s"
    chance: 25
    cost: 16
    type: armor
    events:
      - armorself
    function: potion
    effects:
      - DAMAGE_RESISTANCE
    duration: 6
    amplifier: 0
    thresholdself: 40
  tolerance-iii:
    name: "&eTolerance III"
    lore:
      - "&7Gives resistance after taking more"
      - "&7than a certain amount of damage."
      - "&7Resistance I at 40% health - 8s"
    chance: 25
    cost: 32
    type: armor
    events:
      - armorself
    function: potion
    effects:
      - DAMAGE_RESISTANCE
    duration: 8
    amplifier: 0
    thresholdself: 40