main: com.gmail.evstike.AdvancedWeapons.Fates
name: AdvancedWeapons
version: 1.4.6
author: miner328
depend: [Vault]
softdepend: [ActionBarAPI]
api-version: 1.13
description: Conquer enemies with custom enchanted gear and powerful magical items.
commands:
  advancedweapons:
    description: Plugin information
    aliases: [aw, advweapons]
  enchgui:
    description: Select enchantments from a menu
    aliases: [awenchgui, ench, enchants]
  weapons:
    description: Receive magical weapons
    aliases: [awweapons, buyweapons]
  machines:
    description: Power up ancient machinery
    aliases: [awmachines, buymachines]
  ignite:
    description: Ignite a player on fire
    aliases: [awignite, fire]
  hidden:
    description: Completely hide yourself from players
    aliases: [awhidden, hide]
  dust:
    description: Access your dust vault
    aliases: [awdust]
  ce:
    description: Enchant your items with custom enchantments
    aliases: [awce, awenchantments, customenchants]
  coinflip:
    description: Challenge someone to a coinflip match
    aliases: [cflip, awcoinflip]
permissions:
  advancedweapons.*:
    description: All AdvancedWeapons permission nodes
    default: op
    children:
      advancedweapons.ce: true
      advancedweapons.advancedweapons: true
      advancedweapons.dust: true
      advancedweapons.weapons: true
      advancedweapons.machines: true
      advancedweapons.coinflip: true
      advancedweapons.enchgui: true
      advancedweapons.hidden: true
      advancedweapons.ignite: true
      advancedweapons.admin: true
      advancedweapons.reload: true
      advancedweapons.permissions: true
  advancedweapons.player:
    description: Default AdvancedWeapons permission nodes
    default: true
    children:
      advancedweapons.ce: true
      advancedweapons.advancedweapons: true
      advancedweapons.dust: true
      advancedweapons.weapons: true
      advancedweapons.machines: true
      advancedweapons.coinflip: true
  advancedweapons.admin:
    description: Admin commands
    default: op
    children:
      advancedweapons.enchgui: true
      advancedweapons.hidden: true
      advancedweapons.ignite: true
      advancedweapons.reload: true
      advancedweapons.permissions: true
  advancedweapons.advancedweapons:
    description: /advancedweapons
    default: op
  advancedweapons.ce:
    description: /ce
    default: op
  advancedweapons.weapons:
    description: /weapons
    default: op
  advancedweapons.machines:
    description: /machines
    default: op
  advancedweapons.dust:
    description: /dust
    default: op
  advancedweapons.coinflip:
    description: /coinflip
    default: op
  advancedweapons.enchgui:
    description: /enchgui
    default: op
  advancedweapons.hidden:
    description: /hidden
    default: op
  advancedweapons.ignite:
    description: /ignite
    default: op
  advancedweapons.reload:
    description: /advancedweapons reload
    default: op
  advancedweapons.permissions:
    description: /advancedweapons permissions
    default: op